### ISSUE TITLE
Entry submit should check Multiple Choice answers

### ISSUE THREAD

**Issue by Rpd-Strike** [TeamUnibuc/SmartForms#25]
Currently the endpoint `/api/entry/{formId}` does not even use the parameter `formId`

In the same time it should check for the multiple-choice questions that the answer is valid (i.e. is found in the given options)

[Entry router python file](https://github.com/TeamUnibuc/SmartForms/blob/aa3536637f88747e81dec3cc4a717654889e24f4/backend/sources/routers/entry_router.py#L59)
```python
async def entry_submit_form(entry: smart_forms_types.FormAnswer, formId: str):
    """
        Submits a new entry for a given form.
    """
    db = database.get_collection(database.ENTRIES)

    db.insert_one(entry.to_dict())
    return "ok"
```

**Comment by theodormoroianu** [comment]
Yes, entry router is a mess, a lot of stuff doesn't really make sense right now.

I am working on it.

**Comment by theodormoroianu** [comment]
Closing this issue, as most of the entry router has been fully re-implemented.
