### ISSUE TITLE
Multiple choice answer index

### ISSUE THREAD

**Issue by Rpd-Strike** [TeamUnibuc/SmartForms#26]
Did not think a lot about it, however, we should consider the idea of also returning the index of the selected answer when doing inference or when returning the form answers, and when submitting form answers?

Has to be decided depending on needs / objectives

**Comment by theodormoroianu** [comment]
Right now, the flow is the following:
1. Users submit files to the inference API endpoint.
2. Files are parsed, and their entries added to the database.
3. A list with all the entries is returned to the client-side.
4. The client side shows the parsed answers to the client, and submits any modification as an "edit".

From the client-side, the only difference between this approach and the previous one is:
1. Even if the client closes the tab BEFORE inference is finished, the entries aren't lost.
2. The client-side doesn't have to re-submit every entry, just the ones modified by the user.
3. The client doesn't have to press a "Confirm inference" or similar button, to commit the entries to the database.
4. It makes it possible to implement the "contiguous learning", where the client-side tells the backend some characters were not recognized correctly.

In the future, we can add a boolean flag `hasBeenValidated` or something similar, to be able to tell which entries were validated by the user.
