### ISSUE TITLE
`/api/form/list` Enhancement

### ISSUE THREAD

**Issue by Rpd-Strike** [TeamUnibuc/SmartForms#44]
Currently, the endpoint does this:
`Returns the list of all available forms, made by the user. If the user is not signed in, then all forms are returned.`

I think we should use a route/query parameter in a way such that I can query for:
- My own forms if (if logged)
- All available forms that are not mine (if logged in)
- All available forms (if not logged / if I specify this)

Doesn't really matter how you decide to do that, but if I have these 3 things I can do some cool UI stuff

**Comment by theodormoroianu** [comment]
The description is a little bit misleading.
If `AUTHENTICATION_CHECKS` is disabled, then all users are in god-mode, they can edit anything they want, so we return all the forms.

if `AUTHENTICATION_CHECKS` is enabled, then:
1. If the user is logged in, then only his/her forms are returned.
2. If the user is not logged in, then the endpoint returns a status code of 202 (user is not authenticated).

The idea is that a user shouldn't be able to just browse available forms made by others, unless he is provided with a link (which acts as an authentication (only users knowing the URL can submit to the form, like Google docs with a public link).

**Comment by Rpd-Strike** [comment]
I made some cool animations on PR #47 and I just want to have 2 lists of forms to showcase them.

We can repurpose the categories like this:
1. Forms that can receive entries and are owned by the user. (based on the `canBeFilledOnline` property)
2. Forms that can not receive entries but are still owned by the user.
3. For the forms not owned by the user, we can show only the cards with very little info. (Being unable to send entries to them showing maybe only title, nr questions, and nr of entries).  Or we can add another property to a form: `publicStats` and/or `publicSending` to control who can view stats and/or add entries.
