### ISSUE TITLE
Unable to specify description of multiple choice question

### ISSUE THREAD

**Issue by theodormoroianu** [TeamUnibuc/SmartForms#79]
We currently do not have the option to change the default description of a multiple-choice question:
![image](https://user-images.githubusercontent.com/8684801/170365195-9f51e855-887b-44da-b0aa-c99c3bed2141.png)

The result is always:
![image](https://user-images.githubusercontent.com/8684801/170365229-2488fab4-2760-42c7-8d46-1da627383b8d.png)

**Comment by Rpd-Strike** [comment]
Solved by #82
