### ISSUE TITLE
Listing all forms

### ISSUE THREAD

**Issue by Rpd-Strike** [TeamUnibuc/SmartForms#81]
Querying the endpoint `/api/form/list` currently doesn't send forms created by another user but is marked as public.

We will refer to `signIn`  as the option `needsToBeSignedInToSubmit` and `filling` as shorthand for `canBeFilledOnline`
* Visibility stands for if the client should receive data about the form from the api/backend
* can complete stands for if the client should be able to complete the form and submit

We should decide when to do in these cases:

When the user is signed and:
* `filling` and `signIn`:  visibility - YES | can complete - YES
* `filling`: visibility - NO | can complete - YES
* `signIn`: visibility - NO  | can complete - NO  <Here the `signIn` setting it's weaker than `filling`>
* nothing: visibility - NO | can complete - NO

**Note:** Even if visibility should be NO by the above rules, if the user is the owner he should still be able to view and edit the forms

When the user is not logged in:
* `filling` and `signIn`: visibility - YES | can complete - NO
* `filling`: visibility - NO | can complete - YES
* `signIn`: visibility - NO | can complete - NO   <Here the `signIn` setting it's weaker than `filling`>
* nothing: visibility - NO | can complete - NO

**Comment by Rpd-Strike** [comment]
We should think about the difference between 'Accepting entries for a form' and 'Listing the form publicly' on the main page. Currently we can not distinguish between the two and the differentiator is basically, we show the form to users if they are logged and `filling` and `signIn` is marked. 

I think there are actually 3 distinct settings we care about:
1. `Filling`: The form is accepting new entries
2. `Public`: The form is publicly listed and as such it appears on the main page either if you are logged in or not
3. `SignedIn`: If the user should be signed in when completing a form.

I think for MVP purposes we can keep the actual system, WDYT?

*Note for the future*: The 3rd point can be made more complex by requiring emails from some specific organization.

**Comment by theodormoroianu** [comment]
We could keep the current system, I will implement the functionality asap, and am merging right now the fix to make the list endpoint work.

**Comment by Rpd-Strike** [comment]
IS this done? I see that you updated the entry. If yes, you can close this issue
