### ISSUE TITLE
Frontend should redirect when a task is done.

### ISSUE THREAD

**Issue by theodormoroianu** [TeamUnibuc/SmartForms#85]
As a user, when I add an answer, when I create a form etc I get a nice message stating "The ... was added / created".

The frontend could also redirect the user to said form (when creating a form), or to the form description (when filling a form).

**Comment by Rpd-Strike** [comment]
Solved by #90

**Comment by Rpd-Strike** [comment]
@theodormoroianu  Feel free to close this issue if you believe how it works now is satisfactory, otherwise, leave a comment here
