### ISSUE TITLE
SmartForms.ml freezes when user is not logged in

### ISSUE THREAD

**Issue by theodormoroianu** [TeamUnibuc/SmartForms#86]
SmartForms crashes (and the entire page turns white). Error message: `index.e9b01772.js:151 Uncaught TypeError: Cannot read properties of undefined (reading 'length')`

Steps to reproduce:
1. Logout of smartforms.ml
2. Go to "Create Form"
3. Click on "Create PDF"

Reason:
Backend refuses to return a pdf form, and returns
```JSON
{
  "statusCode": 202,
  "message": "User is not authenticated!"
}
```
The frontend does not expect this and crashes.
This happens also when creating a form, but the frontend displays "Error occured :/" instead.

Fix:
Backend can stop refusing PDF generation even if users are not logged in, as the database is not altered by a PDF preview call.
The frontend should display a better message why PDF generation or form creation failed. (Maybe ask users to login before allowing them to create a form?).

**Comment by Rpd-Strike** [comment]
Fixed by #88
